### ISSUE TITLE
ReadFFmpeg and WriteFFmpeg nodes should be rewritten

### ISSUE THREAD

**Issue by cgvirus** [NatronGitHub/openfx-io#2]
https://github.com/NatronGitHub/Natron/issues/329
The next update cycle should include up to date FFMpeg otherwise Natron will fall behind in 4K intermediaries . Also HEVEC is getting it's edge with Nvidia. 
Let me know please, where should I check or include the library in read/write node for compatibility check. It will help me to learn building OFX as well. Thanks
@devernay

**Comment by devernay** [comment]
Issue https://github.com/NatronGitHub/Natron/issues/329 isn't an issue with the FFmpeg library itself, but with the ReadFFmpeg and WriteFFmpeg nodes. These have to be reworked, and it takes some real effort, due to the complexity of the FFmpeg libraries. Take a look at the https://github.com/FFmpeg/FFmpeg/blob/master/fftools/ffplay.c source to get an idea.

**Comment by devernay** [comment]
Other relevant issues: https://github.com/NatronGitHub/Natron/issues/241 https://github.com/NatronGitHub/Natron/issues/231 https://github.com/NatronGitHub/Natron/issues/148

**Comment by cgvirus** [comment]
Seems to be a very wrong project as a startup for me! Alright. I will then follow your ofx guideline and will start with some simple one first then. Thanks.

**Comment by devernay** [comment]
done!

**Comment by cgvirus** [comment]
Awesome! Will check! Thanks!

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/openfx-io/pull/5 and https://github.com/NatronGitHub/openfx-io/pull/6
